
import java.util.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.AbstractAction;
import javax.swing.JDialog;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Main_Frame extends javax.swing.JFrame {
        boolean ok=false;
        public Database data=new Database();
        DefaultTableModel dtm;

    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        MathTextField = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JSCE");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Создать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Добавить строку");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Сохранить");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Загрузить");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Добавить столбец");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Поиск по таблице");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Рассчитать");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(MathTextField)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(33, 33, 33)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dtm=(DefaultTableModel)jTable1.getModel();
        if (dtm.getColumnCount()!=0)
        {
            int opcion = JOptionPane.showConfirmDialog(null, "Хотите сохранить таблицу?", "Подтверждение", JOptionPane.YES_NO_OPTION);

            if (opcion == 0) { //The ISSUE is here
                dothesave();
            }
        }
        String z = JOptionPane.showInputDialog("Введите размер");
        int n=Integer.parseInt(z);
        data.columns=n;
        data.columns_names = new String[n];
        for (int i=0; i<n;i++)
        {
            z=JOptionPane.showInputDialog("Введите название колонки");
            data.columns_names[i]=z;
        }       
        jTable1.setModel(new javax.swing.table.DefaultTableModel(null,data.columns_names));
        ok=true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dtm=(DefaultTableModel)jTable1.getModel();
        if (dtm.getColumnCount()!=0) {
        Add_Frame a=new Add_Frame();
        String[] colname=new String[dtm.getColumnCount()];
        for (int i=0; i<dtm.getColumnCount(); i++)
        {
            colname[i]=dtm.getColumnName(i);
        }
        a.settableprop_row(colname);
        a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        a.setVisible(true);
        a.addWindowListener( new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent we) {
        String[] nf=new String[dtm.getColumnCount()];
        nf=a.geteditedrow();
        dtm.addRow(nf);
        }
        } );
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dothesave();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dtm=(DefaultTableModel)jTable1.getModel();
        if (dtm.getColumnCount()!=0)
        {
            int opcion = JOptionPane.showConfirmDialog(null, "Хотите сохранить таблицу?", "Подтверждение", JOptionPane.YES_NO_OPTION);

            if (opcion == 0) { //The ISSUE is here
                dothesave();
            }
        }      
            JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Database file","dat","*.*");
            fc.setFileFilter(filter);
            fc.addChoosableFileFilter(filter);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            if ( fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION ) 
            {
               try  
               {
                   File fi = fc.getSelectedFile();
                   BufferedReader fr = new BufferedReader(new FileReader(fi.getPath()));
                   String[] ss2;
                   String ss1;
                   data.cells.clear();
                   boolean first_line=true;
                    while ((ss1 = fr.readLine()) != null) 
                    {
                        ss2=ss1.split("_");
                        if (first_line==false)
                        {
                            data.columns=ss2.length;
                            data.cells.add(ss2);
                        }
                        else
                        {
                            data.columns_names=ss1.split("_");
                            first_line=false;
                        }
                    }
                    fr.close();
               }
            catch ( IOException e ) 
                {
                    System.out.println(e.getMessage());
                }
            }
        String[][] array = new String[data.cells.size()][];
        for (int i = 0; i < data.cells.size(); i++) {
        String[] row = data.cells.get(i);
        array[i] = row;
        }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(array,data.columns_names));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            
            dtm=(DefaultTableModel)jTable1.getModel();
            if (dtm.getColumnCount()!=0)
            {
            String z=JOptionPane.showInputDialog("Введите название колонки");
            String[][] jj=new String[1][dtm.getColumnCount()];
            Add_Frame b=new Add_Frame();
            b.settableprop_col(z,dtm.getRowCount());
            b.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            b.setVisible(true);
            b.addWindowListener( new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
            String[] nf=b.geteditedcol();
            dtm.addColumn(z);
           String[] newcols=new String[dtm.getRowCount()];
           for (int i=0; i<dtm.getRowCount(); i++)
           {
               newcols[i]=dtm.getColumnName(i);
           }
           data.columns_names=newcols;
            data.columns=dtm.getColumnCount();
           for (int i=0; i<dtm.getRowCount(); i++)
           {
               dtm.setValueAt(nf[i], i, data.columns-1);
           }
            }
            } );
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String z=JOptionPane.showInputDialog("Введите ключ");
        if (z!=null){
        dtm=(DefaultTableModel)jTable1.getModel();
        Search_frame a=new Search_frame();
        a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        a.setVisible(true);
        a.changetable(dtm,z,data);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String S=MathTextField.getText();
        MathThingyes a=new MathThingyes();
        MathTextField.setText(a.calc(S,(DefaultTableModel)jTable1.getModel()));
    }//GEN-LAST:event_jButton7ActionPerformed

    void dothesave() {
        dtm=(DefaultTableModel)jTable1.getModel();
        String S="";
        for (int i=0; i<dtm.getColumnCount(); i++)
        {
            S+=dtm.getColumnName(i)+"_";
        }
        S+='\n';
        for (int i=0; i<dtm.getRowCount(); i++)
        {
            for (int j=0; j<dtm.getColumnCount(); j++)
            {
                S+=dtm.getValueAt(i, j)+"_";
            }
            S+='\n';
        }
        JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Database file","dat");
            fc.setFileFilter(filter);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            if ( fc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION ) 
            {
                try 
                {
                    FileWriter fw;
                    File fi = fc.getSelectedFile();
                    String ext=fi.getName();
                    if (!ext.endsWith(".dat"))
                    {
                        fw = new FileWriter(fc.getSelectedFile()+".dat");
                    }
                    else
                    {
                        fw = new FileWriter(fc.getSelectedFile());
                    }
                    fw.write(S);
                    fw.flush();
                }
            catch ( IOException e ) 
                {
                    System.out.println(e.getMessage());
                }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MathTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
